name: Build and Publish storybook to GitHub Pages
on:
  push:
    branches:
      - "main"
      - "hotfix/cicd"
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout if required
        uses: actions/checkout@v3
  
      - name: 'Build'
        shell: bash
        run: |
          echo "::group::Build"
          cd src && npm ci
          npm run build-storybook
          echo "::endgroup::"
  
      - name: 'upload'
        uses: actions/upload-pages-artifact@v1.0.4
        with: 
          path: src/storybook-static
  
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ github.token }}
